// Generated by `bun init`
type AddTodo = (newTodo: string) => void;
type Todo = {
  text: string;
  complete: boolean;
}
type ToggleComplete = (selectedTodo: Todo) => void
type EditTodo = (selectedTodo: Todo, editText: string) => void
declare module "*.svg" {
  /**
   * A path to the SVG file
   */
  const path: `${string}.svg`;
  export = path;
}

declare module "*.css" {}

declare module "*.module.css" {
  /**
   * A record of class names to their corresponding CSS module classes
   */
  const classes: { readonly [key: string]: string };
  export = classes;
}
